edition: 1.0.0
name: paddle-ocr
access: default

services:
  paddle-ocr:
    component: fc
    props:
      region: cn-shanghai
      service:
        name: paddle-ocr
        description: paddle-ocr service
      function:
        name: paddle-ocr-function
        runtime: custom-container
        memorySize: 1024
        caPort: 8080
        codeUri: ./
        timeout: 60
        customContainerConfig:
          image: 'registry.cn-shanghai.aliyuncs.com/custom-container/paddle-ocr:0.0.2'
          command: '["python"]'
          args: '["index.py"]'
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
